basePath: /v1
definitions:
  ExtensionResponse:
    properties:
      code:
        type: integer
      data:
        type: any
      error:
        type: string
    type: object
  ent.Group:
    properties:
      created_at:
        description: CreatedAt holds the value of the "created_at" field.
        type: string
      id:
        description: ID of the ent.
        type: integer
      name:
        description: Name holds the value of the "name" field.
        type: string
      option:
        $ref: '#/definitions/entity.GroupOption'
        description: Option holds the value of the "option" field.
      share_url:
        description: ShareURL holds the value of the "share_url" field.
        type: string
      uid:
        description: UID holds the value of the "uid" field.
        type: string
    type: object
  entity.GroupOption:
    properties:
      tags:
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /v1/ext/{uid}:
    post:
      consumes:
      - application/json
      description: store one or more tab group
      parameters:
      - description: groups
        in: body
        name: groups
        required: true
        schema:
          items:
            $ref: '#/definitions/ent.Group'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ExtensionResponse'
            - properties:
                data:
                  type: object
              type: object
      tags:
      - add
  /v1/ext/register:
    post:
      description: get uid
      parameters:
      - description: client name
        in: query
        maxLength: 64
        minLength: 1
        name: name
        required: true
        type: string
      - description: extension id
        in: query
        maxLength: 256
        minLength: 1
        name: extension
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ExtensionResponse'
            - properties:
                data:
                  allOf:
                  - type: object
                  - properties:
                      uid:
                        type: string
                    type: object
              type: object
      tags:
      - extension
swagger: "2.0"
