// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExtensionClientsColumns holds the columns for the "extension_clients" table.
	ExtensionClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "extension_id", Type: field.TypeString, Unique: true},
		{Name: "last_access_time", Type: field.TypeTime},
	}
	// ExtensionClientsTable holds the schema information for the "extension_clients" table.
	ExtensionClientsTable = &schema.Table{
		Name:       "extension_clients",
		Columns:    ExtensionClientsColumns,
		PrimaryKey: []*schema.Column{ExtensionClientsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExtensionClientsTable,
	}
)

func init() {
}
