// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BarkAddressesColumns holds the columns for the "bark_addresses" table.
	BarkAddressesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "target", Type: field.TypeString},
		{Name: "index", Type: field.TypeInt64},
	}
	// BarkAddressesTable holds the schema information for the "bark_addresses" table.
	BarkAddressesTable = &schema.Table{
		Name:       "bark_addresses",
		Columns:    BarkAddressesColumns,
		PrimaryKey: []*schema.Column{BarkAddressesColumns[0]},
	}
	// ExtensionClientsColumns holds the columns for the "extension_clients" table.
	ExtensionClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "extension_id", Type: field.TypeString},
		{Name: "client_uid", Type: field.TypeUUID, Unique: true},
		{Name: "last_access_time", Type: field.TypeTime},
	}
	// ExtensionClientsTable holds the schema information for the "extension_clients" table.
	ExtensionClientsTable = &schema.Table{
		Name:       "extension_clients",
		Columns:    ExtensionClientsColumns,
		PrimaryKey: []*schema.Column{ExtensionClientsColumns[0]},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "share_url", Type: field.TypeString, Nullable: true},
		{Name: "option", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "seq", Type: field.TypeInt32},
		{Name: "extension_client_groups", Type: field.TypeInt, Nullable: true},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "groups_extension_clients_groups",
				Columns:    []*schema.Column{GroupsColumns[7]},
				RefColumns: []*schema.Column{ExtensionClientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TabsColumns holds the columns for the "tabs" table.
	TabsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "seq", Type: field.TypeInt32},
		{Name: "favicon", Type: field.TypeString, Nullable: true},
		{Name: "uid", Type: field.TypeUUID},
		{Name: "group_tabs", Type: field.TypeInt, Nullable: true},
	}
	// TabsTable holds the schema information for the "tabs" table.
	TabsTable = &schema.Table{
		Name:       "tabs",
		Columns:    TabsColumns,
		PrimaryKey: []*schema.Column{TabsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tabs_groups_tabs",
				Columns:    []*schema.Column{TabsColumns[6]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ExtensionClientAddressesColumns holds the columns for the "extension_client_addresses" table.
	ExtensionClientAddressesColumns = []*schema.Column{
		{Name: "extension_client_id", Type: field.TypeInt},
		{Name: "bark_address_id", Type: field.TypeInt},
	}
	// ExtensionClientAddressesTable holds the schema information for the "extension_client_addresses" table.
	ExtensionClientAddressesTable = &schema.Table{
		Name:       "extension_client_addresses",
		Columns:    ExtensionClientAddressesColumns,
		PrimaryKey: []*schema.Column{ExtensionClientAddressesColumns[0], ExtensionClientAddressesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "extension_client_addresses_extension_client_id",
				Columns:    []*schema.Column{ExtensionClientAddressesColumns[0]},
				RefColumns: []*schema.Column{ExtensionClientsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "extension_client_addresses_bark_address_id",
				Columns:    []*schema.Column{ExtensionClientAddressesColumns[1]},
				RefColumns: []*schema.Column{BarkAddressesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BarkAddressesTable,
		ExtensionClientsTable,
		GroupsTable,
		TabsTable,
		ExtensionClientAddressesTable,
	}
)

func init() {
	GroupsTable.ForeignKeys[0].RefTable = ExtensionClientsTable
	TabsTable.ForeignKeys[0].RefTable = GroupsTable
	ExtensionClientAddressesTable.ForeignKeys[0].RefTable = ExtensionClientsTable
	ExtensionClientAddressesTable.ForeignKeys[1].RefTable = BarkAddressesTable
}
