// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notification/ent/extensionclient"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExtensionClientCreate is the builder for creating a ExtensionClient entity.
type ExtensionClientCreate struct {
	config
	mutation *ExtensionClientMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ecc *ExtensionClientCreate) SetName(s string) *ExtensionClientCreate {
	ecc.mutation.SetName(s)
	return ecc
}

// SetExtensionID sets the "extension_id" field.
func (ecc *ExtensionClientCreate) SetExtensionID(s string) *ExtensionClientCreate {
	ecc.mutation.SetExtensionID(s)
	return ecc
}

// SetLastAccessTime sets the "last_access_time" field.
func (ecc *ExtensionClientCreate) SetLastAccessTime(t time.Time) *ExtensionClientCreate {
	ecc.mutation.SetLastAccessTime(t)
	return ecc
}

// Mutation returns the ExtensionClientMutation object of the builder.
func (ecc *ExtensionClientCreate) Mutation() *ExtensionClientMutation {
	return ecc.mutation
}

// Save creates the ExtensionClient in the database.
func (ecc *ExtensionClientCreate) Save(ctx context.Context) (*ExtensionClient, error) {
	var (
		err  error
		node *ExtensionClient
	)
	if len(ecc.hooks) == 0 {
		if err = ecc.check(); err != nil {
			return nil, err
		}
		node, err = ecc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ExtensionClientMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ecc.check(); err != nil {
				return nil, err
			}
			ecc.mutation = mutation
			if node, err = ecc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ecc.hooks) - 1; i >= 0; i-- {
			if ecc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ecc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ecc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ecc *ExtensionClientCreate) SaveX(ctx context.Context) *ExtensionClient {
	v, err := ecc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecc *ExtensionClientCreate) Exec(ctx context.Context) error {
	_, err := ecc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecc *ExtensionClientCreate) ExecX(ctx context.Context) {
	if err := ecc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ecc *ExtensionClientCreate) check() error {
	if _, ok := ecc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ExtensionClient.name"`)}
	}
	if _, ok := ecc.mutation.ExtensionID(); !ok {
		return &ValidationError{Name: "extension_id", err: errors.New(`ent: missing required field "ExtensionClient.extension_id"`)}
	}
	if _, ok := ecc.mutation.LastAccessTime(); !ok {
		return &ValidationError{Name: "last_access_time", err: errors.New(`ent: missing required field "ExtensionClient.last_access_time"`)}
	}
	return nil
}

func (ecc *ExtensionClientCreate) sqlSave(ctx context.Context) (*ExtensionClient, error) {
	_node, _spec := ecc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ecc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ecc *ExtensionClientCreate) createSpec() (*ExtensionClient, *sqlgraph.CreateSpec) {
	var (
		_node = &ExtensionClient{config: ecc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: extensionclient.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: extensionclient.FieldID,
			},
		}
	)
	if value, ok := ecc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: extensionclient.FieldName,
		})
		_node.Name = value
	}
	if value, ok := ecc.mutation.ExtensionID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: extensionclient.FieldExtensionID,
		})
		_node.ExtensionID = value
	}
	if value, ok := ecc.mutation.LastAccessTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: extensionclient.FieldLastAccessTime,
		})
		_node.LastAccessTime = value
	}
	return _node, _spec
}

// ExtensionClientCreateBulk is the builder for creating many ExtensionClient entities in bulk.
type ExtensionClientCreateBulk struct {
	config
	builders []*ExtensionClientCreate
}

// Save creates the ExtensionClient entities in the database.
func (eccb *ExtensionClientCreateBulk) Save(ctx context.Context) ([]*ExtensionClient, error) {
	specs := make([]*sqlgraph.CreateSpec, len(eccb.builders))
	nodes := make([]*ExtensionClient, len(eccb.builders))
	mutators := make([]Mutator, len(eccb.builders))
	for i := range eccb.builders {
		func(i int, root context.Context) {
			builder := eccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExtensionClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, eccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, eccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, eccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (eccb *ExtensionClientCreateBulk) SaveX(ctx context.Context) []*ExtensionClient {
	v, err := eccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eccb *ExtensionClientCreateBulk) Exec(ctx context.Context) error {
	_, err := eccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eccb *ExtensionClientCreateBulk) ExecX(ctx context.Context) {
	if err := eccb.Exec(ctx); err != nil {
		panic(err)
	}
}
