// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notification/ent/extensionclient"
	"notification/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	uuid "github.com/satori/go.uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeExtensionClient = "ExtensionClient"
)

// ExtensionClientMutation represents an operation that mutates the ExtensionClient nodes in the graph.
type ExtensionClientMutation struct {
	config
	op               Op
	typ              string
	id               *int
	name             *string
	extension_id     *string
	client_uid       *uuid.UUID
	last_access_time *time.Time
	clearedFields    map[string]struct{}
	done             bool
	oldValue         func(context.Context) (*ExtensionClient, error)
	predicates       []predicate.ExtensionClient
}

var _ ent.Mutation = (*ExtensionClientMutation)(nil)

// extensionclientOption allows management of the mutation configuration using functional options.
type extensionclientOption func(*ExtensionClientMutation)

// newExtensionClientMutation creates new mutation for the ExtensionClient entity.
func newExtensionClientMutation(c config, op Op, opts ...extensionclientOption) *ExtensionClientMutation {
	m := &ExtensionClientMutation{
		config:        c,
		op:            op,
		typ:           TypeExtensionClient,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withExtensionClientID sets the ID field of the mutation.
func withExtensionClientID(id int) extensionclientOption {
	return func(m *ExtensionClientMutation) {
		var (
			err   error
			once  sync.Once
			value *ExtensionClient
		)
		m.oldValue = func(ctx context.Context) (*ExtensionClient, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().ExtensionClient.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withExtensionClient sets the old ExtensionClient of the mutation.
func withExtensionClient(node *ExtensionClient) extensionclientOption {
	return func(m *ExtensionClientMutation) {
		m.oldValue = func(context.Context) (*ExtensionClient, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ExtensionClientMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ExtensionClientMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ExtensionClientMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ExtensionClientMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().ExtensionClient.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ExtensionClientMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ExtensionClientMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the ExtensionClient entity.
// If the ExtensionClient object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExtensionClientMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ExtensionClientMutation) ResetName() {
	m.name = nil
}

// SetExtensionID sets the "extension_id" field.
func (m *ExtensionClientMutation) SetExtensionID(s string) {
	m.extension_id = &s
}

// ExtensionID returns the value of the "extension_id" field in the mutation.
func (m *ExtensionClientMutation) ExtensionID() (r string, exists bool) {
	v := m.extension_id
	if v == nil {
		return
	}
	return *v, true
}

// OldExtensionID returns the old "extension_id" field's value of the ExtensionClient entity.
// If the ExtensionClient object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExtensionClientMutation) OldExtensionID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExtensionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExtensionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExtensionID: %w", err)
	}
	return oldValue.ExtensionID, nil
}

// ResetExtensionID resets all changes to the "extension_id" field.
func (m *ExtensionClientMutation) ResetExtensionID() {
	m.extension_id = nil
}

// SetClientUID sets the "client_uid" field.
func (m *ExtensionClientMutation) SetClientUID(u uuid.UUID) {
	m.client_uid = &u
}

// ClientUID returns the value of the "client_uid" field in the mutation.
func (m *ExtensionClientMutation) ClientUID() (r uuid.UUID, exists bool) {
	v := m.client_uid
	if v == nil {
		return
	}
	return *v, true
}

// OldClientUID returns the old "client_uid" field's value of the ExtensionClient entity.
// If the ExtensionClient object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExtensionClientMutation) OldClientUID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldClientUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldClientUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldClientUID: %w", err)
	}
	return oldValue.ClientUID, nil
}

// ResetClientUID resets all changes to the "client_uid" field.
func (m *ExtensionClientMutation) ResetClientUID() {
	m.client_uid = nil
}

// SetLastAccessTime sets the "last_access_time" field.
func (m *ExtensionClientMutation) SetLastAccessTime(t time.Time) {
	m.last_access_time = &t
}

// LastAccessTime returns the value of the "last_access_time" field in the mutation.
func (m *ExtensionClientMutation) LastAccessTime() (r time.Time, exists bool) {
	v := m.last_access_time
	if v == nil {
		return
	}
	return *v, true
}

// OldLastAccessTime returns the old "last_access_time" field's value of the ExtensionClient entity.
// If the ExtensionClient object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ExtensionClientMutation) OldLastAccessTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastAccessTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastAccessTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastAccessTime: %w", err)
	}
	return oldValue.LastAccessTime, nil
}

// ResetLastAccessTime resets all changes to the "last_access_time" field.
func (m *ExtensionClientMutation) ResetLastAccessTime() {
	m.last_access_time = nil
}

// Where appends a list predicates to the ExtensionClientMutation builder.
func (m *ExtensionClientMutation) Where(ps ...predicate.ExtensionClient) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *ExtensionClientMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (ExtensionClient).
func (m *ExtensionClientMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ExtensionClientMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, extensionclient.FieldName)
	}
	if m.extension_id != nil {
		fields = append(fields, extensionclient.FieldExtensionID)
	}
	if m.client_uid != nil {
		fields = append(fields, extensionclient.FieldClientUID)
	}
	if m.last_access_time != nil {
		fields = append(fields, extensionclient.FieldLastAccessTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ExtensionClientMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case extensionclient.FieldName:
		return m.Name()
	case extensionclient.FieldExtensionID:
		return m.ExtensionID()
	case extensionclient.FieldClientUID:
		return m.ClientUID()
	case extensionclient.FieldLastAccessTime:
		return m.LastAccessTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ExtensionClientMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case extensionclient.FieldName:
		return m.OldName(ctx)
	case extensionclient.FieldExtensionID:
		return m.OldExtensionID(ctx)
	case extensionclient.FieldClientUID:
		return m.OldClientUID(ctx)
	case extensionclient.FieldLastAccessTime:
		return m.OldLastAccessTime(ctx)
	}
	return nil, fmt.Errorf("unknown ExtensionClient field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ExtensionClientMutation) SetField(name string, value ent.Value) error {
	switch name {
	case extensionclient.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case extensionclient.FieldExtensionID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExtensionID(v)
		return nil
	case extensionclient.FieldClientUID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetClientUID(v)
		return nil
	case extensionclient.FieldLastAccessTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastAccessTime(v)
		return nil
	}
	return fmt.Errorf("unknown ExtensionClient field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ExtensionClientMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ExtensionClientMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ExtensionClientMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown ExtensionClient numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ExtensionClientMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ExtensionClientMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ExtensionClientMutation) ClearField(name string) error {
	return fmt.Errorf("unknown ExtensionClient nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ExtensionClientMutation) ResetField(name string) error {
	switch name {
	case extensionclient.FieldName:
		m.ResetName()
		return nil
	case extensionclient.FieldExtensionID:
		m.ResetExtensionID()
		return nil
	case extensionclient.FieldClientUID:
		m.ResetClientUID()
		return nil
	case extensionclient.FieldLastAccessTime:
		m.ResetLastAccessTime()
		return nil
	}
	return fmt.Errorf("unknown ExtensionClient field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ExtensionClientMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ExtensionClientMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ExtensionClientMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ExtensionClientMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ExtensionClientMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ExtensionClientMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ExtensionClientMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown ExtensionClient unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ExtensionClientMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown ExtensionClient edge %s", name)
}
