// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notification/ent/group"
	"notification/ent/tab"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	uuid "github.com/satori/go.uuid"
)

// TabCreate is the builder for creating a Tab entity.
type TabCreate struct {
	config
	mutation *TabMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (tc *TabCreate) SetName(s string) *TabCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetURL sets the "url" field.
func (tc *TabCreate) SetURL(s string) *TabCreate {
	tc.mutation.SetURL(s)
	return tc
}

// SetSeq sets the "seq" field.
func (tc *TabCreate) SetSeq(i int32) *TabCreate {
	tc.mutation.SetSeq(i)
	return tc
}

// SetFavicon sets the "favicon" field.
func (tc *TabCreate) SetFavicon(s string) *TabCreate {
	tc.mutation.SetFavicon(s)
	return tc
}

// SetNillableFavicon sets the "favicon" field if the given value is not nil.
func (tc *TabCreate) SetNillableFavicon(s *string) *TabCreate {
	if s != nil {
		tc.SetFavicon(*s)
	}
	return tc
}

// SetUID sets the "uid" field.
func (tc *TabCreate) SetUID(u uuid.UUID) *TabCreate {
	tc.mutation.SetUID(u)
	return tc
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (tc *TabCreate) SetGroupID(id int) *TabCreate {
	tc.mutation.SetGroupID(id)
	return tc
}

// SetNillableGroupID sets the "group" edge to the Group entity by ID if the given value is not nil.
func (tc *TabCreate) SetNillableGroupID(id *int) *TabCreate {
	if id != nil {
		tc = tc.SetGroupID(*id)
	}
	return tc
}

// SetGroup sets the "group" edge to the Group entity.
func (tc *TabCreate) SetGroup(g *Group) *TabCreate {
	return tc.SetGroupID(g.ID)
}

// Mutation returns the TabMutation object of the builder.
func (tc *TabCreate) Mutation() *TabMutation {
	return tc.mutation
}

// Save creates the Tab in the database.
func (tc *TabCreate) Save(ctx context.Context) (*Tab, error) {
	var (
		err  error
		node *Tab
	)
	if len(tc.hooks) == 0 {
		if err = tc.check(); err != nil {
			return nil, err
		}
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TabMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tc.check(); err != nil {
				return nil, err
			}
			tc.mutation = mutation
			if node, err = tc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			if tc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TabCreate) SaveX(ctx context.Context) *Tab {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TabCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TabCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tc *TabCreate) check() error {
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tab.name"`)}
	}
	if _, ok := tc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Tab.url"`)}
	}
	if _, ok := tc.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "Tab.seq"`)}
	}
	if _, ok := tc.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Tab.uid"`)}
	}
	return nil
}

func (tc *TabCreate) sqlSave(ctx context.Context) (*Tab, error) {
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (tc *TabCreate) createSpec() (*Tab, *sqlgraph.CreateSpec) {
	var (
		_node = &Tab{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tab.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tab.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tab.FieldName,
		})
		_node.Name = value
	}
	if value, ok := tc.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tab.FieldURL,
		})
		_node.URL = value
	}
	if value, ok := tc.mutation.Seq(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: tab.FieldSeq,
		})
		_node.Seq = value
	}
	if value, ok := tc.mutation.Favicon(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tab.FieldFavicon,
		})
		_node.Favicon = value
	}
	if value, ok := tc.mutation.UID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: tab.FieldUID,
		})
		_node.UID = value
	}
	if nodes := tc.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tab.GroupTable,
			Columns: []string{tab.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: group.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_tabs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TabCreateBulk is the builder for creating many Tab entities in bulk.
type TabCreateBulk struct {
	config
	builders []*TabCreate
}

// Save creates the Tab entities in the database.
func (tcb *TabCreateBulk) Save(ctx context.Context) ([]*Tab, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Tab, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TabMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TabCreateBulk) SaveX(ctx context.Context) []*Tab {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TabCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TabCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
