// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"notification/ent/extensionclient"
	"notification/ent/tabhistory"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TabHistoryCreate is the builder for creating a TabHistory entity.
type TabHistoryCreate struct {
	config
	mutation *TabHistoryMutation
	hooks    []Hook
}

// SetURL sets the "url" field.
func (thc *TabHistoryCreate) SetURL(s string) *TabHistoryCreate {
	thc.mutation.SetURL(s)
	return thc
}

// SetName sets the "name" field.
func (thc *TabHistoryCreate) SetName(s string) *TabHistoryCreate {
	thc.mutation.SetName(s)
	return thc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (thc *TabHistoryCreate) SetNillableName(s *string) *TabHistoryCreate {
	if s != nil {
		thc.SetName(*s)
	}
	return thc
}

// SetIcon sets the "icon" field.
func (thc *TabHistoryCreate) SetIcon(s string) *TabHistoryCreate {
	thc.mutation.SetIcon(s)
	return thc
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (thc *TabHistoryCreate) SetNillableIcon(s *string) *TabHistoryCreate {
	if s != nil {
		thc.SetIcon(*s)
	}
	return thc
}

// SetHistoryListID sets the "history_list" edge to the ExtensionClient entity by ID.
func (thc *TabHistoryCreate) SetHistoryListID(id int) *TabHistoryCreate {
	thc.mutation.SetHistoryListID(id)
	return thc
}

// SetNillableHistoryListID sets the "history_list" edge to the ExtensionClient entity by ID if the given value is not nil.
func (thc *TabHistoryCreate) SetNillableHistoryListID(id *int) *TabHistoryCreate {
	if id != nil {
		thc = thc.SetHistoryListID(*id)
	}
	return thc
}

// SetHistoryList sets the "history_list" edge to the ExtensionClient entity.
func (thc *TabHistoryCreate) SetHistoryList(e *ExtensionClient) *TabHistoryCreate {
	return thc.SetHistoryListID(e.ID)
}

// Mutation returns the TabHistoryMutation object of the builder.
func (thc *TabHistoryCreate) Mutation() *TabHistoryMutation {
	return thc.mutation
}

// Save creates the TabHistory in the database.
func (thc *TabHistoryCreate) Save(ctx context.Context) (*TabHistory, error) {
	var (
		err  error
		node *TabHistory
	)
	if len(thc.hooks) == 0 {
		if err = thc.check(); err != nil {
			return nil, err
		}
		node, err = thc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TabHistoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = thc.check(); err != nil {
				return nil, err
			}
			thc.mutation = mutation
			if node, err = thc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(thc.hooks) - 1; i >= 0; i-- {
			if thc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = thc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, thc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (thc *TabHistoryCreate) SaveX(ctx context.Context) *TabHistory {
	v, err := thc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (thc *TabHistoryCreate) Exec(ctx context.Context) error {
	_, err := thc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thc *TabHistoryCreate) ExecX(ctx context.Context) {
	if err := thc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (thc *TabHistoryCreate) check() error {
	if _, ok := thc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "TabHistory.url"`)}
	}
	return nil
}

func (thc *TabHistoryCreate) sqlSave(ctx context.Context) (*TabHistory, error) {
	_node, _spec := thc.createSpec()
	if err := sqlgraph.CreateNode(ctx, thc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (thc *TabHistoryCreate) createSpec() (*TabHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &TabHistory{config: thc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tabhistory.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tabhistory.FieldID,
			},
		}
	)
	if value, ok := thc.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tabhistory.FieldURL,
		})
		_node.URL = value
	}
	if value, ok := thc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tabhistory.FieldName,
		})
		_node.Name = value
	}
	if value, ok := thc.mutation.Icon(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tabhistory.FieldIcon,
		})
		_node.Icon = value
	}
	if nodes := thc.mutation.HistoryListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tabhistory.HistoryListTable,
			Columns: []string{tabhistory.HistoryListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: extensionclient.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.extension_client_histories = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TabHistoryCreateBulk is the builder for creating many TabHistory entities in bulk.
type TabHistoryCreateBulk struct {
	config
	builders []*TabHistoryCreate
}

// Save creates the TabHistory entities in the database.
func (thcb *TabHistoryCreateBulk) Save(ctx context.Context) ([]*TabHistory, error) {
	specs := make([]*sqlgraph.CreateSpec, len(thcb.builders))
	nodes := make([]*TabHistory, len(thcb.builders))
	mutators := make([]Mutator, len(thcb.builders))
	for i := range thcb.builders {
		func(i int, root context.Context) {
			builder := thcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TabHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, thcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, thcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, thcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (thcb *TabHistoryCreateBulk) SaveX(ctx context.Context) []*TabHistory {
	v, err := thcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (thcb *TabHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := thcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (thcb *TabHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := thcb.Exec(ctx); err != nil {
		panic(err)
	}
}
