basePath: /v1
definitions:
  ExtensionResponse:
    properties:
      code:
        type: integer
      data:
        type: any
      error:
        type: string
    type: object
  pb.Client:
    properties:
      ext_id:
        type: string
      groups:
        items:
          $ref: '#/definitions/pb.Group'
        type: array
      last_access_time:
        type: integer
      name:
        type: string
      uid:
        type: string
    type: object
  pb.Group:
    properties:
      index:
        type: integer
      name:
        type: string
      option:
        $ref: '#/definitions/pb.GroupOption'
      tabs:
        items:
          $ref: '#/definitions/pb.Tab'
        type: array
      uid:
        type: string
    type: object
  pb.GroupOption:
    properties:
      tags:
        items:
          type: string
        type: array
    type: object
  pb.Tab:
    properties:
      favicon:
        type: string
      index:
        type: integer
      name:
        type: string
      uid:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /ext/{uid}/{group}/:
    delete:
      consumes:
      - application/json
      description: remove tab group and all tabs
      parameters:
      - description: client uid
        in: path
        name: uid
        required: true
        type: string
      - description: group uid
        in: path
        name: group
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ExtensionResponse'
      tags:
      - remove
  /ext/{uid}/{group}/{tab}:
    delete:
      consumes:
      - application/json
      description: remove tab
      parameters:
      - description: client uid
        in: path
        name: uid
        required: true
        type: string
      - description: group uid
        in: path
        name: group
        required: true
        type: string
      - description: tab uid
        in: path
        name: tab
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ExtensionResponse'
      tags:
      - remove
  /ext/{uid}/group:
    get:
      consumes:
      - application/json
      description: get client's all groups and tabs
      parameters:
      - description: client uid
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ExtensionResponse'
            - properties:
                data:
                  $ref: '#/definitions/pb.Client'
              type: object
      tags:
      - pull
    post:
      consumes:
      - application/json
      description: store one or more tab group
      parameters:
      - description: client uid
        in: path
        name: uid
        required: true
        type: string
      - description: groups
        in: body
        name: groups
        required: true
        schema:
          items:
            $ref: '#/definitions/pb.Group'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ExtensionResponse'
      tags:
      - add
  /ext/{uid}/swap/tab:
    post:
      consumes:
      - application/json
      description: swap 2 tab
      parameters:
      - description: client uid
        in: path
        name: uid
        required: true
        type: string
      - description: group(a) uid
        in: query
        name: groupA
        required: true
        type: string
      - description: group(b) uid
        in: query
        name: groupB
        required: true
        type: string
      - description: group(a) tab(a) uid
        in: query
        name: tabA
        required: true
        type: string
      - description: group(b) tab(b) uid
        in: query
        name: tabB
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ExtensionResponse'
      tags:
      - modify
  /ext/register:
    post:
      description: get uid
      parameters:
      - description: client name
        in: query
        maxLength: 64
        minLength: 1
        name: name
        required: true
        type: string
      - description: extension id
        in: query
        maxLength: 256
        minLength: 1
        name: extension
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ExtensionResponse'
            - properties:
                data:
                  allOf:
                  - type: object
                  - properties:
                      uid:
                        type: string
                    type: object
              type: object
      tags:
      - extension
swagger: "2.0"
