// Code generated by entc, DO NOT EDIT.

package extensionclient

const (
	// Label holds the string label denoting the extensionclient type in the database.
	Label = "extension_client"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldExtensionID holds the string denoting the extension_id field in the database.
	FieldExtensionID = "extension_id"
	// FieldLastAccessTime holds the string denoting the last_access_time field in the database.
	FieldLastAccessTime = "last_access_time"
	// Table holds the table name of the extensionclient in the database.
	Table = "extension_clients"
)

// Columns holds all SQL columns for extensionclient fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldExtensionID,
	FieldLastAccessTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
