// Code generated by entc, DO NOT EDIT.

package extensionclient

const (
	// Label holds the string label denoting the extensionclient type in the database.
	Label = "extension_client"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldExtensionID holds the string denoting the extension_id field in the database.
	FieldExtensionID = "extension_id"
	// FieldClientUID holds the string denoting the client_uid field in the database.
	FieldClientUID = "client_uid"
	// FieldLastAccessTime holds the string denoting the last_access_time field in the database.
	FieldLastAccessTime = "last_access_time"
	// EdgeGroups holds the string denoting the groups edge name in mutations.
	EdgeGroups = "groups"
	// Table holds the table name of the extensionclient in the database.
	Table = "extension_clients"
	// GroupsTable is the table that holds the groups relation/edge.
	GroupsTable = "groups"
	// GroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupsInverseTable = "groups"
	// GroupsColumn is the table column denoting the groups relation/edge.
	GroupsColumn = "extension_client_groups"
)

// Columns holds all SQL columns for extensionclient fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldExtensionID,
	FieldClientUID,
	FieldLastAccessTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ExtensionIDValidator is a validator for the "extension_id" field. It is called by the builders before save.
	ExtensionIDValidator func(string) error
)
