// Code generated by entc, DO NOT EDIT.

package tabhistory

const (
	// Label holds the string label denoting the tabhistory type in the database.
	Label = "tab_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// EdgeHistoryList holds the string denoting the history_list edge name in mutations.
	EdgeHistoryList = "history_list"
	// Table holds the table name of the tabhistory in the database.
	Table = "tab_histories"
	// HistoryListTable is the table that holds the history_list relation/edge.
	HistoryListTable = "tab_histories"
	// HistoryListInverseTable is the table name for the ExtensionClient entity.
	// It exists in this package in order to avoid circular dependency with the "extensionclient" package.
	HistoryListInverseTable = "extension_clients"
	// HistoryListColumn is the table column denoting the history_list relation/edge.
	HistoryListColumn = "extension_client_histories"
)

// Columns holds all SQL columns for tabhistory fields.
var Columns = []string{
	FieldID,
	FieldURL,
	FieldName,
	FieldIcon,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "tab_histories"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"extension_client_histories",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
