// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ExtensionClient is the predicate function for extensionclient builders.
type ExtensionClient func(*sql.Selector)
